import AddDogForm from "@/components/AddDogForm";
import { Dog } from "@/utils/types";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [dogs, setDogs] = useState<Dog[]>([]);
  useEffect(() => {
    fetch("/api/dogs")
      .then(res => res.json())
      .then(dogs => setDogs(dogs as Dog[]));
  }, []);
  return (
    <>
      <Head>
        <title>Dogs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AddDogForm setDogs={setDogs} />
        {dogs.length > 0 &&
          dogs.map((dog, index) => (
            <li key={index}>
              <h2>{dog.name}</h2>
              <p>Nicknames: {dog.nicknames[0]}</p>
              <p>Is this dog fluffy? {dog.isFluffy ? "True" : "Rough"}</p>
              <p>Dog age: {dog.age}</p>
              <p>Dog size: {dog.size}</p>
            </li>
          ))}
      </main>
    </>
  );
}
